import "Converters\BoolToObjectConverter.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass BoolToVisibilityConverter : BoolToObjectConverter
    {
        BoolToVisibilityConverter();
    }
}
