namespace MiniDumpExplorer
{
    [default_interface]
    [Windows.UI.Xaml.Data.Bindable]
    runtimeclass GlobalOptionItems : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        GlobalOptionItems();

        Boolean DisplayHexadecimalNumericFormat;

        Boolean SizeNumberDisplayUnitFormatAuto;
        Boolean SizeNumberDisplayUnitFormatBytes;
        Boolean SizeNumberDisplayUnitFormatKilobytes;
        Boolean SizeNumberDisplayUnitFormatMegabytes;
        Boolean SizeNumberDisplayUnitFormatGigabytes;
        Boolean SizeNumberDisplayUnitFormatTerabytes;
        Boolean SizeNumberDisplayUnitFormatPetabytes;
        Boolean SizeNumberDisplayUnitFormatExabytes;
        Boolean SizeNumberDisplayUnitFormatRaw;

        Boolean SizeNumberDisplayPrintFormatFull;
        Boolean SizeNumberDisplayPrintFormatCompact;

        Boolean SizeNumberDisplayBase16;
        Boolean SizeNumberDisplayBase10;

        Boolean TimeStampLocaleLocal;
        Boolean TimeStampLocaleUtc;
        Boolean TimeStampLocaleDumpFile;
        Boolean DateFormatLongDate;
        Boolean DateFormatShortDate;
        Boolean DateFormatUseAltCalendar;
        Boolean DateFormatYearMonth;
        Boolean DateFormatMonthDay;
        Boolean DateFormatLeftToRightReading;
        Boolean DateFormatRightToLeftReading;
        Boolean DateFormatAutoLayout;
        Boolean TimeFormat24Hour;
        Boolean TimeFormatNoTimeMarker;
        Boolean TimeFormatNoSeconds;
        Boolean TimeFormatNoMinutesOrSeconds;

        Boolean DurationFormatTimeSpan;
        Boolean DurationFormatAuto;
        Boolean DurationFormatMilliseconds;
        Boolean DurationFormatSeconds;
        Boolean DurationFormatMinutes;
        Boolean DurationFormatHours;
        Boolean DurationFormatDays;
        Boolean DurationFormatWeeks;
        Boolean DurationFormatMonths;
        Boolean DurationFormatYears;
        Boolean DurationFormatRaw;
    }
}
