import "Models\VsFixedFileInfo.idl";
import "Models\CvInfoPdb70.idl";
import "Models\MiniDumpLocationDescriptor.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    [Windows.UI.Xaml.Data.Bindable]
    runtimeclass ModuleListStreamEntry : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ModuleListStreamEntry();

        UInt32 Index { get; };
        String Name { get; };
        String Path { get; };
        UInt32 CheckSum { get; };
        UInt64 BaseOfImage { get; };
        UInt32 SizeOfImage { get; };
        UInt32 BuildFileHash { get; };
        VsFixedFileInfo FileInfo { get; };
        MiniDumpLocationDescriptor CvRecord { get; };
        CvInfoPdb70 PdbInfo { get; };
        MiniDumpLocationDescriptor MiscRecord { get; };
        UInt64 Reserved0 { get; };
        UInt64 Reserved1 { get; };
    }
}
