import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass RecentFileItemsDataSource : IDataGridDataSource
    {
        RecentFileItemsDataSource();
    }
}
