import "Models/MiniDumpMemoryDescriptor.idl";
import "Models/ThreadContext.idl";
import "Models/ThreadStack.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    [Windows.UI.Xaml.Data.Bindable]
    runtimeclass ThreadExListStreamEntry : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ThreadExListStreamEntry();

        UInt32 Index { get; };
        UInt32 Id { get; };
        String Name { get; };
        UInt32 Priority { get; };
        UInt32 PriorityClass { get; };
        String PriorityClassType { get; };
        UInt32 SuspendCount { get; };
        UInt64 TEB { get; };
        Boolean HasBackingStore{ get; };
        MiniDumpMemoryDescriptor BackingStore { get; };
        String BackingStoreHexDump { get; };
        ThreadStack Stack { get; };
        ThreadContext ThreadContext{ get; };
    }
}
