import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass UnloadedModuleListStreamEntriesDataSource : IDataGridDataSource
    {
        UnloadedModuleListStreamEntriesDataSource();
    }
}
