import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass XStateDataEnabledFeaturesDataSource : IDataGridDataSource
    {
        XStateDataEnabledFeaturesDataSource();
    }
}
