import "Models\M128A.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    [Windows.UI.Xaml.Data.Bindable]
    runtimeclass YmmRegister : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        YmmRegister();

        String Name{ get; };
        UInt32 Index{ get; };
        M128A Xmm{ get; };
        M128A Ymm{ get; };
    }
}
