namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass BooleanToVisibilityConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        BooleanToVisibilityConverter();
        Boolean IsReversed;
    }
}
