namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass Category 
    {
        Category();

        String Name;
        String CategoryIcon;
        Windows.Foundation.Collections.IObservableVector<Category> Children;
        Boolean IsLeaf;
    }
}
