import "IDumpFileStreamX64ThreadContext.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamX64ThreadContext : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamX64ThreadContext();

        IDumpFileStreamX64ThreadContext ThreadContext;
    }
}
