import "IDumpFileStreamComment.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamComment : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamComment(IDumpFileStreamComment stream);

        IDumpFileStreamComment Stream { get; };
    }
}
