import "IDumpFileStreamThreadContext.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamThreadContext : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamThreadContext();

        IDumpFileStreamThreadContext ThreadContext;
    }
}
