import "IDumpFileStreamComment.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamCommentView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamCommentView(IDumpFileStreamComment stream);

        IDumpFileStreamComment Stream { get; };
    }
}
