import "IDumpFileHeader.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpHeader : Windows.UI.Xaml.Controls.UserControl
    {
        DumpHeader(IDumpFileHeader header);

        IDumpFileHeader Header { get; };
        String HeaderType { get; };
        Boolean IsKernelDumpFile { get; };
        Boolean IsUserDumpFile { get; };
        Boolean IsInvalidDumpFile { get; };
        Boolean IsUserOrInvalidDumpFile { get; };
    }
}
