import "IDumpFileStreamException.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamException : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamException(IDumpFileStreamException stream);
    
        IDumpFileStreamException Stream { get; };
    }
}
