import "IDumpFileStreamModuleList.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamModuleListView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamModuleListView(IDumpFileStreamModuleList stream);

        IDumpFileStreamModuleList Stream { get; };
    }
}
