import "IDumpFileStreamMiscInfo.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamMiscInfoView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamMiscInfoView(IDumpFileStreamMiscInfo stream);

        IDumpFileStreamMiscInfo Stream { get; };
    }
}
