import "IDumpFileStreamX64ThreadContext.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamX64ThreadContextView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamX64ThreadContextView();

        IDumpFileStreamX64ThreadContext ThreadContext;
    }
}
