import "IDumpFileStreamSystemInfo.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamSystemInfoView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamSystemInfoView(IDumpFileStreamSystemInfo stream);

        IDumpFileStreamSystemInfo Stream { get; };
    }
}
