import "IDumpFileStreamX86ThreadContext.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamX86ThreadContext : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamX86ThreadContext();

        IDumpFileStreamX86ThreadContext ThreadContext;
        Boolean HasExtendedRegisters;
    }
}
