namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpStreamHandleOperationListView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpStreamHandleOperationListView();
    }
}
