import "Category.idl";
import "IDumpFile.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DumpFileView : Windows.UI.Xaml.Controls.UserControl
    {
        DumpFileView(String path, String display_name, IDumpFile dump_file);

        String Path;
        String DisplayName;
        Windows.Foundation.Collections.IObservableVector<Category> Categories{ get; };
    }
}
