import "IX86CpuInfo.idl";
import "IOtherCpuInfo.idl";

namespace MiniDumpExplorer
{
    interface ICpuInformation
    {
        IX86CpuInfo X86CpuInfo { get; };
        IOtherCpuInfo OtherCpuInfo { get; };
    }
}
