import "IMiniDumpMiscInfo.idl";
import "IMiniDumpMiscInfo2.idl";
import "IMiniDumpMiscInfo3.idl";
import "IMiniDumpMiscInfo4.idl";
import "IMiniDumpMiscInfo5.idl";

namespace MiniDumpExplorer
{
    interface IDumpFileStreamMiscInfo
    {
        UInt64 Index { get; };
        Boolean IsValid { get; };
        UInt64 MiscInfoVersion { get; };
        IMiniDumpMiscInfo MiscInfo { get; };
        IMiniDumpMiscInfo2 MiscInfo2 { get; };
        IMiniDumpMiscInfo3 MiscInfo3 { get; };
        IMiniDumpMiscInfo4 MiscInfo4 { get; };
        IMiniDumpMiscInfo5 MiscInfo5 { get; };
    }
}
