import "DumpFileType.idl";

namespace MiniDumpExplorer
{
    interface IDumpFileHeader
    {
        enum DumpFileType Type { get; };
        String TypeString { get; };
        Boolean IsValid { get; };
        String VersionString { get; };
        UInt32 Signature { get; };
        UInt16 Version { get; };
        UInt16 InternalVersion { get; };
        UInt32 NumberOfStreams { get; };
        UInt32 StreamDirectoryRva { get; };
        UInt32 CheckSum { get; };
        Windows.Foundation.DateTime TimeDateStamp { get; };
        UInt64 Flags { get; };
        Windows.Foundation.Collections.IObservableVector<String> FlagTypes { get; };
    }
}
