import "DumpFileType.idl";
import "IDumpFileHeader.idl";
import "IDumpFileStream.idl";

namespace MiniDumpExplorer
{
    interface IDumpFile
    {
        enum DumpFileType Type { get; };
        Boolean HasHeader { get; };
        IDumpFileHeader Header { get; };
        Windows.Foundation.Collections.IVector<IDumpFileStream> Streams { get; };
    }
}
