import "MiniDumpModuleProxy.idl";

namespace MiniDumpExplorer
{
    interface IDumpFileStreamModuleList
    {
        UInt64 Index { get; };
        Windows.Foundation.Collections.IObservableVector<MiniDumpModuleProxy> Modules { get; };
    }
}
