import "IMiniDumpException.idl";
import "IDumpFileStreamThreadContext.idl";
import "IStackTrace.idl";

namespace MiniDumpExplorer
{
    interface IDumpFileStreamException
    {
        UInt64 Index { get; };
        Boolean IsValid { get; };
        UInt32 ThreadId { get; };
        IMiniDumpException ExceptionRecord { get; };
        IDumpFileStreamThreadContext ThreadContext { get; };
        Boolean HasStackTrace { get; };
        IStackTrace StackTrace { get; };
    }
}
