import "IWow64FloatingSaveArea.idl";

namespace MiniDumpExplorer
{
    interface IDumpFileStreamX86ThreadContext
    {
        UInt32 ContextFlags { get; };
        UInt32 Dr0 { get; };
        UInt32 Dr1 { get; };
        UInt32 Dr2 { get; };
        UInt32 Dr3 { get; };
        UInt32 Dr6 { get; };
        UInt32 Dr7 { get; };
        IWow64FloatingSaveArea FloatSave { get; };
        UInt32 SegGs { get; };
        UInt32 SegFs { get; };
        UInt32 SegEs { get; };
        UInt32 SegDs { get; };
        UInt32 Edi { get; };
        UInt32 Esi { get; };
        UInt32 Ebx { get; };
        UInt32 Edx { get; };
        UInt32 Ecx { get; };
        UInt32 Eax { get; };
        UInt32 Ebp { get; };
        UInt32 Eip { get; };
        UInt32 SegCs { get; };
        UInt32 EFlags { get; };
        UInt32 Esp { get; };
        UInt32 SegSs { get; };
        UInt8[] ExtendedRegisters { get; };

        String ExtendedRegistersHexDump { get; };
    }
}
