namespace MiniDumpExplorer
{
    interface IMiniDumpProcessVmCounters1
    {
        UInt16 Revision { get; };
        UInt32 PageFaultCount { get; };
        UInt64 PeakWorkingSetSize { get; };
        UInt64 WorkingSetSize { get; };
        UInt64 QuotaPeakPagedPoolUsage { get; };
        UInt64 QuotaPagedPoolUsage { get; };
        UInt64 QuotaPeakNonPagedPoolUsage { get; };
        UInt64 QuotaNonPagedPoolUsage { get; };
        UInt64 PagefileUsage { get; };
        UInt64 PeakPagefileUsage { get; };
        UInt64 PrivateUsage { get; };
    }
}
