namespace MiniDumpExplorer
{
    interface IMiniDumpMiscInfo
    {
        UInt32 Flags1{ get; };
        Boolean HasProcessId{ get; };
        UInt32 ProcessId{ get; };
        Boolean HasProcessTimes{ get; };
        Windows.Foundation.DateTime ProcessCreateTime{ get; };
        UInt32 ProcessUserTime{ get; };
        UInt32 ProcessKernelTime{ get; };
    }
}
