namespace MiniDumpExplorer
{
    interface IMiniDumpMiscInfo2
    {
        Boolean HasProcessPowerInfo{ get; };
        UInt32 ProcessorMaxMhz{ get; };
        UInt32 ProcessorCurrentMhz{ get; };
        UInt32 ProcessorMhzLimit{ get; };
        UInt32 ProcessorMaxIdleState{ get; };
        UInt32 ProcessorCurrentIdleState{ get; };
    }
}
