namespace MiniDumpExplorer
{
    interface IMiniDumpException
    {
        UInt32 ExceptionCode { get; };
        String ExceptionCodeString { get; };
        UInt32 ExceptionFlags { get; };
        String ExceptionFlagsString { get; };
        UInt64 ExceptionRecord { get; };
        UInt64 ExceptionAddress { get; };
        UInt32 NumberParameters { get; };
        UInt64[] ExceptionInformation { get; };
        Windows.Foundation.Collections.IObservableVector<String> Parameters { get; };
    }
}
