import "ITimeZoneInformation.idl";

namespace MiniDumpExplorer
{
    interface IMiniDumpMiscInfo3
    {
        Boolean HasProcessIntegrityLevel{ get; };
        UInt32 ProcessIntegrityLevel{ get; };
        String ProcessIntegrityLevelString{ get; };
        Boolean HasProcessExecuteFlags{ get; };
        UInt32 ProcessExecuteFlags{ get; };
        Windows.Foundation.Collections.IObservableVector<String> ProcessExecuteFlagStrings { get; };
        Boolean HasProtectedProcess{ get; };
        UInt32 ProtectedProcess{ get; };
        Boolean HasTimeZone{ get; };
        UInt32 TimeZoneId{ get; };
        ITimeZoneInformation TimeZone{ get; };
    }
}
