namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass IsEqualToVisibilityConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        IsEqualToVisibilityConverter();
        Boolean IsReversed;
        String Value;
    }
}
