namespace MiniDumpExplorer
{
    interface IStackFrame
    {
        UInt64 StackAddress { get; };
        UInt64 Address { get; };
        String ModuleName { get; };
        String SymbolName { get; };
        String FileName { get; };
        UInt32 LineNumber { get; };
        UInt64 ModuleDisplacement { get; };
        UInt64 SymbolDisplacement { get; };
        UInt32 LineDisplacement { get; };
        Boolean InLine { get; };
        Boolean Found { get; };
        Boolean FrameContentFound { get; };
        String DisplayLine { get; };
    }
}
