import "ISystemTime.idl";

namespace MiniDumpExplorer
{
    interface ITimeZoneInformation
    {
        UInt32 Bias{ get; };
        String StandardName{ get; };
        ISystemTime StandardDate{ get; };
        UInt32 StandardBias{ get; };
        String DaylightName{ get; };
        ISystemTime DaylightDate{ get; };
        UInt32 DaylightBias{ get; };
    }
}
