namespace MiniDumpExplorer
{
    interface IVsFixedFileInfo
    {
        UInt32 Signature { get; };
        String StrucVersion { get; };
        String FileVersion { get; };
        String ProductVersion { get; };
        UInt32 FileFlagsMask { get; };
        UInt32 FileFlags { get; };
        Windows.Foundation.Collections.IObservableVector<String> FileFlagTypes { get; };
        UInt32 FileOS { get; };
        Windows.Foundation.Collections.IObservableVector<String> FileOSTypes { get; };
        UInt32 FileType { get; };
        UInt32 FileSubtype { get; };
        String FileTypeString { get; };
        Boolean HasFileDate { get; };
        Windows.Foundation.DateTime FileDate { get; };
    }
}
