namespace MiniDumpExplorer
{
    interface IWow64FloatingSaveArea
    {
        UInt32 ControlWord { get; };
        UInt32 StatusWord { get; };
        UInt32 TagWord { get; };
        UInt32 ErrorOffset { get; };
        UInt32 ErrorSelector { get; };
        UInt32 DataOffset { get; };
        UInt32 DataSelector { get; };
        UInt8[] RegisterArea { get; };
        UInt32 Cr0NpxState { get; };

        String RegisterAreaHexDump { get; };
    }
}
