import "IMiniDumpModule.idl";

namespace MiniDumpExplorer
{
    [bindable]
    [default_interface]
    runtimeclass MiniDumpModuleProxy : IMiniDumpModule
    {
        MiniDumpModuleProxy(IMiniDumpModule inner);
    }
}
