import "IDumpFileStreamMiscInfo.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass MiscInfo3View : Windows.UI.Xaml.Controls.UserControl
    {
        MiscInfo3View();

        IDumpFileStreamMiscInfo Stream;
    }
}
