import "IDumpFileStreamMiscInfo.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass MiscInfo5View : Windows.UI.Xaml.Controls.UserControl
    {
        MiscInfo5View();

        IDumpFileStreamMiscInfo Stream;
    }
}
