import "IDumpFileStreamMiscInfo.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass MiscInfoView : Windows.UI.Xaml.Controls.UserControl
    {
        MiscInfoView();

        IDumpFileStreamMiscInfo Stream;
    }
}
