import "IMiniDumpProcessVmCounters1.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass ProcessVmCounters1View : Windows.UI.Xaml.Controls.UserControl
    {
        ProcessVmCounters1View();
        IMiniDumpProcessVmCounters1 VmCounters;
    }
}
