import "IMiniDumpProcessVmCounters2.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass ProcessVmCounters2View : Windows.UI.Xaml.Controls.UserControl
    {
        ProcessVmCounters2View();
        IMiniDumpProcessVmCounters2 VmCounters;
    }
}
