import "IVsFixedFileInfo.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass VersionInfoView : Windows.UI.Xaml.Controls.UserControl
    {
        VersionInfoView();

        IVsFixedFileInfo VersionInfo;
    }
}
