import "IXStateFeature.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass XStateFeatureView : Windows.UI.Xaml.Controls.UserControl
    {
        XStateFeatureView();

        IXStateFeature Feature;
    }
}
