#pragma once

#include <experimental/generator>
#include <functional>

namespace winrt::MiniDumpExplorer
{
    struct DataGridFillerColumn;
    struct DataGridColumn;

    namespace implementation
    {
        struct DataGrid;
    }
}

namespace DataGridInternal
{

    class DataGridColumnCollection
    {
    public:
        DataGridColumnCollection(winrt::MiniDumpExplorer::implementation::DataGrid* owningGrid);
        ~DataGridColumnCollection();

        DataGridColumnCollection(DataGridColumnCollection const&) = delete;
        DataGridColumnCollection(DataGridColumnCollection &&) = default;

        DataGridColumnCollection& operator=(DataGridColumnCollection const&) = delete;
        DataGridColumnCollection& operator=(DataGridColumnCollection &&) = default;

        int32_t AutoGeneratedColumnCount() const;
        void AutoGeneratedColumnCount(int32_t value) const;

        std::vector<int32_t> const& DisplayIndexMap() const;
        std::vector<int32_t>& DisplayIndexMap();

        winrt::MiniDumpExplorer::DataGridFillerColumn const& FillerColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn FirstColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn FirstVisibleColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn FirstVisibleNonFillerColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn FirstVisibleWritableColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn FirstVisibleScrollingColumn() const;

        std::vector<winrt::MiniDumpExplorer::DataGridColumn> const& ItemsInternal() const;
        std::vector<winrt::MiniDumpExplorer::DataGridColumn>& ItemsInternal();
        winrt::Windows::Foundation::Collections::IObservableVector<winrt::MiniDumpExplorer::DataGridColumn> const& ObservableItems() const;

        winrt::MiniDumpExplorer::DataGridColumn LastVisibleColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn LastVisibleScrollingColumn() const;
        winrt::MiniDumpExplorer::DataGridColumn LastVisibleWritableColumn() const;
        winrt::MiniDumpExplorer::DataGridFillerColumn const& RowGroupSpacerColumn() const;

        int32_t VisibleColumnCount() const;
        double VisibleEdgedColumnsWidth() const;
        int32_t VisibleStarColumnCount() const;

        bool DisplayInOrder(int32_t columnIndex1, int32_t columnIndex2) const;
        bool EnsureRowGrouping(bool rowGrouping);

        void EnsureVisibleEdgedColumnsWidth();
        winrt::MiniDumpExplorer::DataGridColumn GetColumnAtDisplayIndex(int32_t displayIndex) const;
        int32_t GetColumnCount(bool isVisible, bool isFrozen, int32_t fromColumnIndex, int32_t toColumnIndex) const;

        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetDisplayedColumns();
        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetDisplayedColumns(std::function<bool (winrt::MiniDumpExplorer::DataGridColumn const&)> filter) const;
        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetDisplayedColumns(bool reverse, std::function<bool (winrt::MiniDumpExplorer::DataGridColumn const&)> filter) const;
        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetDisplayedColumnsReverse(std::function<bool (winrt::MiniDumpExplorer::DataGridColumn const&)> filter) const;

        winrt::MiniDumpExplorer::DataGridColumn GetFirstColumn(std::optional<bool> isVisible, std::optional<bool> isFrozen, std::optional<bool> isReadOnly) const;
        winrt::MiniDumpExplorer::DataGridColumn GetLastColumn(std::optional<bool> isVisible, std::optional<bool> isFrozen, std::optional<bool> isReadOnly) const;
        winrt::MiniDumpExplorer::DataGridColumn GetNextColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;
        winrt::MiniDumpExplorer::DataGridColumn GetNextColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart,
                                                              std::optional<bool> isVisible,
                                                              std::optional<bool> isFrozen,
                                                              std::optional<bool> isReadOnly) const;
        winrt::MiniDumpExplorer::DataGridColumn GetNextVisibleColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;
        winrt::MiniDumpExplorer::DataGridColumn GetNextVisibleFrozenColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;
        winrt::MiniDumpExplorer::DataGridColumn GetNextVisibleWritableColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;
        winrt::MiniDumpExplorer::DataGridColumn GetPreviousColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart,
                                                                  std::optional<bool> isVisible,
                                                                  std::optional<bool> isFrozen,
                                                                  std::optional<bool> isReadOnly) const;

        winrt::MiniDumpExplorer::DataGridColumn GetPreviousVisibleNonFillerColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;
        winrt::MiniDumpExplorer::DataGridColumn GetPreviousVisibleScrollingColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;
        winrt::MiniDumpExplorer::DataGridColumn GetPreviousVisibleWritableColumn(winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumnStart) const;

        int32_t GetVisibleColumnCount(int32_t fromColumnIndex, int32_t toColumnIndex) const;

        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetVisibleColumns() const;
        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetVisibleFrozenColumns() const;
        std::experimental::generator<winrt::MiniDumpExplorer::DataGridColumn> GetVisibleScrollingColumns() const;

        double GetVisibleFrozenEdgedColumnsWidth() const;

#ifndef NDEBUG
        bool Debug_VerifyColumnDisplayIndexes();
#endif

    private:
        void CollectionChanged([[maybe_unused]] winrt::Windows::Foundation::Collections::IObservableVector<winrt::MiniDumpExplorer::DataGridColumn> const& sender, [[maybe_unused]] winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& event);
        void ClearItems();
        void InsertItem(int32_t columnIndex, winrt::MiniDumpExplorer::DataGridColumn const& dataGridColumn) const;
        void RemoveItem(int32_t columnIndex);

        void RemoveItemPrivate(int32_t columnIndex, bool isSpacer);

    private:
        struct impl;
        std::unique_ptr<impl> impl_;
    };

}

