namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DataGridColumnHeader : Microsoft.UI.Xaml.Controls.ContentControl
    {
        DataGridColumnHeader();

        static Microsoft.UI.Xaml.DependencyProperty SeparatorBrushProperty { get; };
        static Microsoft.UI.Xaml.DependencyProperty SeparatorVisibilityProperty { get; };

        Microsoft.UI.Xaml.Media.Brush SeparatorBrush;
        Microsoft.UI.Xaml.Visibility SeparatorVisibility;
    }
}
