import "Controls\DataGrid\DataGrid.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DataGridGroupItemAutomationPeer
    : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
    , Microsoft.UI.Xaml.Automation.Provider.IExpandCollapseProvider
    , Microsoft.UI.Xaml.Automation.Provider.IGridProvider
    , Microsoft.UI.Xaml.Automation.Provider.IScrollItemProvider
    , Microsoft.UI.Xaml.Automation.Provider.ISelectionProvider
    {
        DataGridGroupItemAutomationPeer(Microsoft.UI.Xaml.Data.ICollectionViewGroup group, DataGrid dataGrid);
    }
}
