import "Controls\DataGrid\DataGridRow.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass DataGridRowAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
    {
        DataGridRowAutomationPeer(DataGridRow owner);
    }
}
