namespace MiniDumpExplorer
{
    enum DataGridSelectionMode
    {
        /// <summary>
        /// Extended DataGridSelectionMode
        /// </summary>
        Extended = 0,

        /// <summary>
        /// Single DataGridSelectionMode
        /// </summary>
        Single = 1
    };
}