namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();

        String SelectedTabTitle { get; };

        Windows.Foundation.IAsyncAction OpenFileInTab(Windows.Storage.StorageFile file);
    }
}
