import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass MemoryListStreamPage : Microsoft.UI.Xaml.Controls.Page
    {
        MemoryListStreamPage();

        IDataGridDataSource ItemsSource { get; };
    }
}
