import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass Memory64ListStreamPage : Microsoft.UI.Xaml.Controls.Page
    {
        Memory64ListStreamPage();

        IDataGridDataSource ItemsSource { get; };
    }
}
