import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass RecentPage : Microsoft.UI.Xaml.Controls.Page
    {
        RecentPage();

        IDataGridDataSource ItemsSource { get; };
    }
}
