namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsPage();

        String Version { get; };
        String OsVersion { get; };
        UInt16 SuiteMask { get; };
        IObservableVector<String> SuiteMaskList{ get; };
        String ProductType { get; };
        String PlatformId { get; };
        String CsdVersion { get; };
        String ProcessorArchitecture { get; };
        Boolean DisplayHexadecimalNumericFormat { get; set; };
    }
}
