import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass StreamsPage : Microsoft.UI.Xaml.Controls.Page
    {
        StreamsPage();

        IDataGridDataSource ItemsSource { get; };
    }
}
