import "Models\ThreadContext.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass ThreadContextView : Microsoft.UI.Xaml.Controls.UserControl
    {
        ThreadContextView();

        ThreadContext ThreadContext { get; set; };
    }
}
