import "Models\ThreadListStreamEntry.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass ThreadEntryPage : Microsoft.UI.Xaml.Controls.Page
    {
        ThreadEntryPage();
        
        ThreadListStreamEntry Thread { get; };
    }
}
