import "Controls\DataGrid\DataGridDataSource.idl";

namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass UnloadedModuleListStreamPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UnloadedModuleListStreamPage();

        IDataGridDataSource ItemsSource { get; };
        
        UInt32 Index { get; };
        UInt32 TotalEntries { get; };
    }
}
