namespace MiniDumpExplorer
{
    [default_interface]
    runtimeclass UnsupportedStreamPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UnsupportedStreamPage();

        UInt32 Index { get; };
        String HexDump { get; };
    }
}
