name: "Visual Studio 2022 x64   "

on: [push, pull_request]

jobs:
  build:
    name: "Windows Visual Studio Build"
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
  
    - name: Build app for release
      run: msbuild DbgHelpUtils.sln -t:rebuild -p:Configuration=Release -p:Platform=x64 -m
  